name: deploy

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print var
        run: echo ${{ secrets.TOKEN_SECRET }}
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
